print("                   ᙠᙝ                  ")
print("╔═════════════════════════════════════╗")
print("║                ⪢Menu⪡               ║")
print("║                                     ║")
print("║ ❥1 Produto                          ║")
print("║ ❥2 Quantidade                       ║")
print("║ ❥3 Peso                             ║")
print("║ ❥4 Marca                            ║")
print("║ ❥5 Preço                            ║")
print("║ ❥6 Cor                              ║")
print("║ ❥7 Tamanho                          ║")
print("║ ❥8 Material                         ║")
print("║ ❥0 Sair                             ║")
print("║                                     ║")
print("╚═════════════════════════════════════╝")
print("                   ᙠᙝ                  ")                 
